In [1]:
#n-dimensional array also called ndarray
#each element take same sizeof block i memory


In [3]:
import numpy as np
a=np.array([1,2,3,4,5,61,2,3,1])
print(a)

[ 1  2  3  4  5 61  2  3  1]


In [6]:
#multi dimension
b=np.array([[1,2,3,4,5],[4,5,6,7,8]])
b

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [11]:
#minimum dimension
c=np.array([1,2,3,4,5,6],ndmin=2)
c

array([[1, 2, 3, 4, 5, 6]])

In [12]:
#dtype parameter
c=np.array([1,2,3,4,5,6],dtype=complex)
c

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

# Numpy -Data Types

In [13]:
#numpy has larger number of data types than the python
# around 19 types