In [3]:
#we will be working with bfew more function of numpy

import numpy as np
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
#lets reshape
a.reshape(2,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

# Item size

In [8]:
#this attribute returns the length of eac element of array in bytes
a.itemsize

8

In [14]:
b=np.array([1,2,3,4,5],dtype=np.int8)
b.itemsize

1

In [15]:
b=np.array([1,2,3,4,5],dtype=np.float32)
b.itemsize

4

In [16]:
#flags that shows current value
b=np.array([1,2,3,4,5],dtype=np.int8)
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# array creation routines

## np.empty

In [26]:
#np.empty can create unitialized array of specified shape and data type
x=np.empty([2,3],dtype=int,order='C')
x

array([[ 94666620760736,               0, 140248741288256],
       [140248741220992, 140249490556160, 140249490544368]])

## np.zeros

In [30]:
#array of five zeros nad dtype is float by default
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
#but we can change the dtype
x = np.zeros((5,), dtype=np.int32)
x

array([0, 0, 0, 0, 0], dtype=int32)

In [35]:
#numpy can also be used with custom data type
x = np.zeros((2,2), dtype=[('x', 'i4'), ('y', 'i4')])
x

array([[(0, 0), (0, 0)],
       [(0, 0), (0, 0)]], dtype=[('x', '<i4'), ('y', '<i4')])

## np.ones