In [3]:
#we will be working with bfew more function of numpy

import numpy as np
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
#lets reshape
a.reshape(2,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

# Item size

In [8]:
#this attribute returns the length of eac element of array in bytes
a.itemsize

8

In [14]:
b=np.array([1,2,3,4,5],dtype=np.int8)
b.itemsize

1

In [15]:
b=np.array([1,2,3,4,5],dtype=np.float32)
b.itemsize

4

In [16]:
#flags that shows current value
b=np.array([1,2,3,4,5],dtype=np.int8)
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# array creation routines

## np.empty

In [26]:
#np.empty can create unitialized array of specified shape and data type
x=np.empty([2,3],dtype=int,order='C')
x

array([[ 94666620760736,               0, 140248741288256],
       [140248741220992, 140249490556160, 140249490544368]])

## np.zeros

In [30]:
#array of five zeros nad dtype is float by default
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
#but we can change the dtype
x = np.zeros((5,), dtype=np.int32)
x

array([0, 0, 0, 0, 0], dtype=int32)

In [35]:
#numpy can also be used with custom data type
x = np.zeros((2,2), dtype=[('x', 'i4'), ('y', 'i4')])
x

array([[(0, 0), (0, 0)],
       [(0, 0), (0, 0)]], dtype=[('x', '<i4'), ('y', '<i4')])

## np.ones

In [36]:
#new array of specified size and type with filled ones

In [39]:
x=np.ones([3,3],dtype=np.float32)
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

# numpy -array from existing data
here we will learn how to create a numpy array using exitsing  data

In [44]:
a=[1,2,3,4,5,6,7,8,9,10]

In [45]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## numpy.asarray

### numpy.asarray(a,dtype=none,order=none) 

In [46]:
#this attribute help hus to convert python squence into nd array

In [47]:
#converting list into array
a=np.asarray(a)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
#lets set data type to float
a=np.asarray(a,dtype=float)

In [49]:
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### nd array from tuple

In [50]:
b=(23,45,67,89,76,66)

In [51]:
b=np.asarray(b,dtype=int)

In [52]:
b

array([23, 45, 67, 89, 76, 66])