In [1]:
import numpy as np

In [7]:
a=np.array([1,2,3])

In [8]:
a

array([1, 2, 3])

In [9]:
b=np.array([(1,3,5),(2,4,6)])

In [10]:
b

array([[1, 3, 5],
       [2, 4, 6]])

In [12]:
c=np.array([(1,3,5),(2,4,6)],dtype=float)

In [13]:
c

array([[1., 3., 5.],
       [2., 4., 6.]])

In [6]:
d=np.array([[(1,2,3,4),(5,6,7,8)],[(12,13,14,15),(16,17,18,19)]])

In [14]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19]]])

In [15]:
#creating an array of zeros

In [22]:
e=np.zeros((3,5),dtype=int)
e

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
#creating arrays of 1
f=np.ones((5,5),dtype=int)
f

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
#a range function
g=np.arange(10,25,5)
g

array([10, 15, 20])

In [30]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [37]:
#random
np.random.random((5,2))

array([[0.09113103, 0.40706239],
       [0.06183433, 0.50618381],
       [0.65836401, 0.78154935],
       [0.32081789, 0.57590549],
       [0.34371481, 0.67228848]])

In [39]:
#np.empty
np.empty((3,2),dtype=int)

array([[4607182418800017408, 4613937818241073152],
       [4617315517961601024, 4611686018427387904],
       [4616189618054758400, 4618441417868443648]])

# Array Mathematics

In [44]:
x=np.array([5,6,7,8,9])
x

array([5, 6, 7, 8, 9])

In [55]:
y=np.array([1,1,2,3, 4])
y

array([1, 1, 2, 3, 4])

In [50]:
x-y

array([5, 5, 5, 5, 5])

In [51]:
x+y

array([ 5,  7,  9, 11, 13])

In [52]:
x*y

array([ 0,  6, 14, 24, 36])

In [56]:
x/y

array([5.        , 6.        , 3.5       , 2.66666667, 2.25      ])

In [57]:
np.multiply(56,78)

4368

In [58]:
np.exp(10)

22026.465794806718

In [59]:
np.sqrt(625)

25.0

In [60]:
np.sin(30)

-0.9880316240928618

In [63]:
np.log(10000)

9.210340371976184

In [64]:
e.dot(67)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [65]:
x.sum()

35

In [66]:
x.min()

5

In [67]:
y.max()

4

In [68]:
x.max()

9

In [73]:
y.corrcoef()

AttributeError: 'numpy.ndarray' object has no attribute 'corrcoef'

In [74]:
np.std(y)

1.16619037896906

In [75]:
np.std(x)

1.4142135623730951